services:
  web:
    build: .
    container_name: receitas-api
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8002"
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    # env_file:
    #   - .env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: receitas-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=receitas_db
      - POSTGRES_USER=receita_user
      - POSTGRES_PASSWORD=receita_password  
    ports:
      - "5432:5432"
volumes:
  postgres_data: 