name: Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "receitas-api"
          path: "."
          format: "HTML"
          out: "dependency-check-report"

      - name: Upload Dependency Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report/dependency-check-report.html

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 flake8-deprecated

      - name: Check for deprecated code
        run: |
          flake8 . --select=DP --show-source
        continue-on-error: false

      - name: Check for deprecated Django code
        run: |
          pip install django-upgrade
          django-upgrade --target-version 5.0 --check .
        continue-on-error: true
      
      - name: Run duplicate code check
        run: |
          bash scripts/check_duplicates.sh
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Start Containers
        run: |
          docker compose -f docker-compose.yml up -d --build
